---
- name: Clone Vol
  hosts: PowerStore
  connection: local

  tasks:
  - name: Clone Volume
    dellemc.powerstore.volume:
      array_ip: "192.168.1.30"
      user: "admin"
      password: "Password123!"
      verifycert: False
      vol_name: "Ansible_Vol"
      clone_volume:
        name: 'AnsibleVolClone'
      state: present