---
- name: Delete Vol
  hosts: PowerStore
  connection: local

  tasks:
  - name: Delete Volume
    dellemc.powerstore.volume:
      array_ip: "192.168.1.30"
      user: "admin"
      password: "Password123!"
      verifycert: False
      vol_id: "68ccf098001426c24e1225b48f215546"
      state: present