---
- name: Resize Vol
  hosts: PowerStore
  connection: local

  tasks:
  - name: Resize Volume
    dellemc.powerstore.volume:
      array_ip: "192.168.1.30"
      user: "admin"
      password: "Password123!"
      verifycert: False
      vol_name: "Ansible_Vol"
      size: "20"
      cap_unit: "GB"
      state: present