---
- name: Storage Info
  hosts: PowerStore
  connection: local

  tasks:
  - name: Get list of volumes, volume groups and node
    dellemc.powerstore.info:
      array_ip: "192.168.1.30"
      validate_certs: "false"
      user: "admin"
      password: "Password123!"
      gather_subset:
        - vol
        - vg
        - node